<?php
// $Id$
$username = "vsmejkal";
/**
 */

/**
 * Implements hook_menu().
 */
function vsmejkal_menu() {
  $items = array();
  
  $items['/admin/vsmejkal'] = array(
    'title' => t('My administration'),
    'description' => t("Administration tools for $username module."),
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => user_access('Admin access'),
	'file' => 'system.admin.inc'
  );  
  
  $items['/admin/vsmejkal/blocks'] = array( // this is an example of configuration link
		'title' => t('My administration blocks') , 
		'description' => t('Add themed blocks to drupalst themes') , 
		'page callback' => '' , 		
		'type' => MENU_NORMAL_ITEM, 
		'access arguments' => array('administer site configuration') ,
	); 
      
  return $items;
  
}
